---
name: "jellyfin-plugin-anime"
guid: "a4df60c5-6ab4-412a-8f79-2cab93fb2bc5"
version: "4" # Please increment with each pull request
jellyfin_version: "10.3.0" # The earliest binary-compatible version
owner: "jellyfin"
nicename: "Anime"
description: "Manage your Anime in Jellyfin"
overview: >
  Manage your Anime in Jellyfin. Supports several different metadata providers and options for
  organizing your collection.
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Anime.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "netstandard2.0"
